[project]
name = "vast-cli-nix"
version = "0.3.1"
description = "Vast CLI packaged for Nix"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "vastai>=0.3.1",
]

[tool.uv]
python-preference = "only-system"
